apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/rendezvoustech/rendezvous-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml
  - patch-resources.yml
  - patch-volumes.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: rendezvous-config

images:
  - name: order-service
    newName: ghcr.io/rendezvoustech/rendezvous-service
    newTag: latest

replicas:
  - count: 1
    name: rendezvous-service