apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendezvous-service
spec:
  template:
    spec:
      containers:
        - name: rendezvous-service
          volumeMounts:
            - name: postgres-credentials-volume
              mountPath: /workspace/secrets/postgres
            - name: rabbitmq-credentials-volume
              mountPath: /workspace/secrets/rabbitmq
            - name: keycloak-issuer-resourceserver-secret-volume
              mountPath: /workspace/secrets/keycloak
      volumes:
        - name: postgres-credentials-volume
          secret:
            secretName: rendezvous-postgres-order-credentials
        - name: rabbitmq-credentials-volume
          secret:
            secretName: rendezvous-rabbitmq-credentials
        - name: keycloak-issuer-resourceserver-secret-volume
          secret:
            secretName: keycloak-issuer-resourceserver-secret