apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/rendezvoustech/rendezvous-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: rendezvous-config

images:
  - name: rendezvous-service
    newName: ghcr.io/rendezvoustech/rendezvous-service
    newTag: latest

replicas:
  - name: rendezvous-service
    count: 1