apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/rendezvoustech/participant-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: participant-config

images:
- name: participant-service
  newName: ghcr.io/rendezvoustech/participant-service
  newTag: 06250747fa8149237905046719aafb3aadf9247e

replicas:
- count: 2
  name: participant-service
