apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/rendezvoustech/participant-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: participant-config

images:
  - name: participant-service
    newName: ghcr.io/rendezvous/participant-service
    newTag: latest

replicas:
  - name: participant-service
    count: 2