global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'edge-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'edge-service:9000' ]
  - job_name: 'participant-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'participant-service:9001' ]
  - job_name: 'rendezvous-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'rendezvous-service:9002' ]
  - job_name: 'config-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'config-service:8888' ]